addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

language: ruby

notifications:
  email: false

rvm:
  - 2.3

script:
  - shellcheck script/**
  - bundle exec reek
  - bundle exec rubocop
  - bundle exec rspec
  - script/mutant.sh
