addons:
  apt:
    packages:
      - shellcheck

language: ruby

notifications:
  email: false

rvm:
  - 2.3

before_script:
  - gem install bundler -v 1.17.2

script:
  - shellcheck script/**
  - bundle exec reek lib spec
  - bundle exec rubocop
  - bundle exec rspec
  - script/mutant.sh
